version: '3.8'

services:
  dotnet-service:
    build:
      context: ./dotnet-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - this-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - dotnet-service
      - python-service
    networks:
      - this-network

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - dotnet-service
    networks:
      - this-network

networks:
  this-network:
    driver: bridge
